rm addons/amxmodx/data/lang/newyear_rbs.txt
rm addons/amxmodx/configs/newyear_rbs/de_cbble.ini
rm addons/amxmodx/configs/newyear_rbs/de_dust2.ini
rm addons/amxmodx/configs/newyear_rbs/de_inferno.ini
rm addons/amxmodx/configs/newyear_rbs/cs_mansion.ini
rm addons/amxmodx/configs/newyear_rbs/de_aztec.ini
rm addons/amxmodx/configs/newyear_rbs/de_nuke.ini
rm addons/amxmodx/configs/newyear_rbs/cs_italy.ini
rm addons/amxmodx/configs/newyear_rbs/de_train.ini
rm addons/amxmodx/configs/newyear_rbs/de_clan1_mill.ini
rm addons/amxmodx/configs/newyear_rbs/de_dust2_2x2.ini
rm addons/amxmodx/configs/newyear_rbs/cs_assault.ini
rm addons/amxmodx/configs/newyear_rbs/de_dust.ini
rm addons/amxmodx/configs/newyear_rbs.cfg
rm addons/amxmodx/plugins/newyear_rbs.amxx
rm addons/amxmodx/modules/amxx_cracker_amxx.dll
rm addons/amxmodx/modules/amxx_cracker_amxx_i386.so
rm addons/amxmodx/modules/sockets2_amxx_i386.so
rm addons/amxmodx/modules/sockets2_readme.txt
rm addons/amxmodx/modules/sockets2_amxx.dll
rm sound/newyear_rbs/jb4.mp3
rm sound/newyear_rbs/jb6.mp3
rm sound/newyear_rbs/jb1.mp3
rm sound/newyear_rbs/jb5.mp3
rm sound/newyear_rbs/jb3.mp3
rm sound/newyear_rbs/jb2.mp3
rm models/newyear_rbs/present3.mdl
rm models/newyear_rbs/cap_te.mdl
rm models/newyear_rbs/v_snow_flash.mdl
rm models/newyear_rbs/snowman2.mdl
rm models/newyear_rbs/p_c4.mdl
rm models/newyear_rbs/cap_ct.mdl
rm models/newyear_rbs/present2.mdl
rm models/newyear_rbs/v_c4.mdl
rm models/newyear_rbs/w_snowball.mdl
rm models/newyear_rbs/snowman5.mdl
rm models/newyear_rbs/tree1.mdl
rm models/newyear_rbs/present1.mdl
rm models/newyear_rbs/tree3.mdl
rm models/newyear_rbs/v_snow_smoke.mdl
rm models/newyear_rbs/v_snow_he.mdl
rm models/newyear_rbs/p_snowball.mdl
rm models/newyear_rbs/w_c4.mdl
rm models/newyear_rbs/snowman1.mdl
rm models/newyear_rbs/snowman4.mdl
rm models/newyear_rbs/tree2.mdl
rm models/newyear_rbs/snowman3.mdl
