rm addons/amxmodx/plugins/zp_addon_knife.sma
rm addons/amxmodx/plugins/zp_addon_knife.amxx
rm sound/knife/combat/knife_miss.wav
rm sound/knife/combat/knife_wall.wav
rm sound/knife/combat/knife_draw.wav
rm sound/knife/combat/knife_slash1.wav
rm sound/knife/combat/knife_slash2.wav
rm sound/knife/combat/knife_hit.wav
rm sound/knife/katana/knife_miss.wav
rm sound/knife/katana/knife_wall.wav
rm sound/knife/katana/knife_draw.wav
rm sound/knife/katana/knife_slash1.wav
rm sound/knife/katana/knife_slash2.wav
rm sound/knife/katana/knife_hit.wav
rm sound/knife/strong/knife_miss.wav
rm sound/knife/strong/knife_wall.wav
rm sound/knife/strong/knife_draw.wav
rm sound/knife/strong/knife_slash1.wav
rm sound/knife/strong/knife_slash2.wav
rm sound/knife/strong/knife_hit.wav
rm sound/knife/kyvald/knife_stab.wav
rm sound/knife/kyvald/knife_miss.wav
rm sound/knife/kyvald/knife_wall.wav
rm sound/knife/kyvald/knife_draw.wav
rm sound/knife/kyvald/knife_slash1.wav
rm sound/knife/kyvald/knife_slash2.wav
rm sound/knife/razor/knife_stab.wav
rm sound/knife/razor/knife_miss.wav
rm sound/knife/razor/knife_wall.wav
rm sound/knife/razor/knife_draw.wav
rm sound/knife/razor/knife_slash1.wav
rm sound/knife/razor/knife_slash2.wav
rm models/zp_knife/combat/v_combat.mdl
rm models/zp_knife/combat/p_combat.mdl
rm models/zp_knife/katana/v_katana.mdl
rm models/zp_knife/katana/p_katana.mdl
rm models/zp_knife/strong/p_strong.mdl
rm models/zp_knife/strong/v_strong.mdl
rm models/zp_knife/kyvald/v_kyvald.mdl
rm models/zp_knife/kyvald/p_kyvald.mdl
rm models/zp_knife/razor/v_razor.mdl
rm models/zp_knife/razor/p_razor.mdl
